#!/bin/bash
set -e

psql <<EOF
CREATE DATABASE origam ENCODING 'UTF8';
\c origam
CREATE SCHEMA origam;
CREATE EXTENSION pgcrypto SCHEMA origam;
CREATE USER origam WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '$USER_PASSWORD';
GRANT CONNECT ON DATABASE origam TO origam;
GRANT ALL PRIVILEGES ON DATABASE origam TO origam;
GRANT ALL ON SCHEMA origam TO origam WITH GRANT OPTION;
EOF