from mcr.microsoft.com/mssql/server:2019-latest as base

# Switch to root to install packages
USER root

# Install SQLCMD
RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc && \
    apt-get clean

ENV PATH="${PATH}:/opt/mssql-tools/bin"

# Restore default user
USER mssql

RUN mkdir /tmp/mssql
WORKDIR /tmp/mssql
RUN touch /tmp/mssql/first
COPY --chown=mssql:root mssqlscript.sh /tmp/mssql
RUN chmod +x mssqlscript.sh
CMD /usr/bin/bash /tmp/mssql/mssqlscript.sh & /opt/mssql/bin/sqlservr > /tmp/output.txt
