#region license
/*
Copyright 2005 - 2021 Advantage Solutions, s. r. o.

This file is part of ORIGAM (http://www.origam.org).

ORIGAM is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ORIGAM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with ORIGAM. If not, see <http://www.gnu.org/licenses/>.
*/
#endregion
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.XPath;
using System.Xml.Xsl;
using Origam.DA.Service;
using Origam.Gui;
using Origam.Schema;
using Origam.Schema.EntityModel;
using Origam.Schema.GuiModel;
using Origam.Schema.MenuModel;
using Origam.Workbench.Services;

namespace Origam.Utils;
public class DocProcessor
{
    private XmlWriter XmlwriterSource { get; set; }
    private XmlWriter Xmlwriter { get; set; }
    private IDocumentationService documentation;
    private MenuSchemaItemProvider menuprovider;
    private readonly IPersistenceService ps;
    private readonly string XsltPath, RootFile, xmlsourcefile, DirectoryPath;
    private MemoryStream mstream;
    public DocProcessor(string path, string xslt, string rootfile, FileStorageDocumentationService documentation, MenuSchemaItemProvider menuprovider, FilePersistenceService persprovider, string xmlfile)
    {
        if (string.IsNullOrEmpty(value: path))
        {
            throw new Exception(message: "Path for Export is not set!");
        }
        xmlsourcefile = xmlfile;
        RootFile = rootfile;
        XsltPath = xslt;
        ps = persprovider ?? throw new Exception(message: "Persprovider  is not set!"); 
        DirectoryPath = string.Join(separator: "", value: path.Split(separator: Path.GetInvalidPathChars()));
        this.documentation = documentation ?? throw new Exception(message: "Documentation  is not set!");
        this.menuprovider = menuprovider ?? throw new Exception(message: "MenuSchemaItemProvider is not set!");
        CreateWriter();
    }
    public DocProcessor(XmlWriter writer, IDocumentationService documentation, IPersistenceService ps)
    {
        XmlwriterSource = writer;
        this.documentation = documentation;
        this.ps = ps;
        CreateWriter();
    }
    private void CreateWriter()
    {
        mstream = new MemoryStream();
        var settings = new XmlWriterSettings
        {
            Encoding = Encoding.UTF8,
            Indent = true
        };
        Xmlwriter = XmlWriter.Create(output: mstream, settings: settings);
        Xmlwriter.WriteStartDocument();
        Xmlwriter.WriteComment(text: "This file is generated by the program.(" + DateTime.Now + ")");
    }
    private void MakeXml(ControlSetItem control, FormControlSet formItem, DataSet dataset, string dataMember)
    {
        string caption, gridCaption, bindingMember, panelTitle, section;
        caption = gridCaption = bindingMember = panelTitle = section = "";
        int tabIndex = 0;
        foreach (var property in control.ChildItemsByType<PropertyValueItem>(itemType: PropertyValueItem.CategoryConst))
        {
            if (property.ControlPropertyItem.Name == "TabIndex")
            {
                tabIndex = property.IntValue;
            }
            if (property.ControlPropertyItem.Name == "Caption")
            {
                caption = property.Value;
            }
            if (property.ControlPropertyItem.Name == "GridColumnCaption")
            {
                gridCaption = property.Value;
            }
            if (property.ControlPropertyItem.Name == "PanelTitle")
            {
                panelTitle = property.Value;
            }
            if (control.ControlItem.IsComplexType && property.ControlPropertyItem.Name == "DataMember")
            {
                dataMember = property.Value;
            }
        }
        caption = (gridCaption == "" | gridCaption == null) ? caption : gridCaption;
        foreach (var bindItem in control.ChildItemsByType<PropertyBindingInfo>(itemType: PropertyBindingInfo.CategoryConst))
        {
            bindingMember = bindItem.Value;
        }
        if (bindingMember != "")
        {
            DataTable table = dataset.Tables[name: FormTools.FindTableByDataMember(ds: dataset, member: dataMember)];
            if (!table.Columns.Contains(name: bindingMember))
            {
                throw new Exception(message: "Field '" + bindingMember +
                                             "' not found in a data structure for the form '" + control.RootItem.Path + "'");
            }
            if (string.IsNullOrEmpty(value: caption))
            {
                caption = table.Columns[name: bindingMember].Caption;
            }
            Guid id = (Guid)table.Columns[name: bindingMember].ExtendedProperties[key: "Id"];
            WriteStartElement(element: "Field", displayName: caption, id: control.ControlItem.Id.ToString(), typeitem: control.ControlItem.GetType().Name);
            WriteElement(caption: "description",
                 description: documentation.GetDocumentation(schemaItemId: id, docType: DocumentationType.USER_LONG_HELP));
        }
        List<ControlSetItem> sortedControls;
        if (control.ControlItem.IsComplexType)
        {
            if (panelTitle != "")
            {
                section = panelTitle;
            }
            else
            {
                section = "Panel";
            }
            if (string.IsNullOrEmpty(value: section))
            {
                section = "Panel";
            }
            AbstractDataEntity entity = GetEntity(ps: ps, dataMember: dataMember, dataset: dataset);
            WriteStartElement(element: "Section", displayName: section, id: control.ControlItem.Id.ToString(), typeitem: control.ControlItem.GetType().Name);
            WriteStartElement(element: "entity");
            WriteElement(caption: "entityid", description: entity.PrimaryKey[key: "Id"].ToString());
            WriteElement(caption: "entityname", description: entity.NodeText);
            WriteEndElement();
            WriteElement(caption: "description",
                description: documentation.GetDocumentation(schemaItemId: control.ControlItem.PanelControlSet.Id, docType: DocumentationType.USER_LONG_HELP));
            sortedControls = control.ControlItem.PanelControlSet.ChildItems[index: 0].ChildItemsByType<ControlSetItem>(itemType: ControlSetItem.CategoryConst);
        }
        else
        {
            sortedControls = control.ChildItemsByType<ControlSetItem>(itemType: ControlSetItem.CategoryConst);
        }
        sortedControls.Sort(comparer: new ControlSetItemComparer());
        foreach (ControlSetItem subControl in sortedControls)
        {
            MakeXml(control: subControl, formItem: formItem, dataset: dataset, dataMember: dataMember);
        }
        if (bindingMember != "")
        {
            WriteEndElement();
        }
        if (section != "")
        {
            WriteEndElement();
        }
    }
    private AbstractDataEntity GetEntity(IPersistenceService ps, string dataMember, DataSet dataset)
    {
        DataTable table = dataset.Tables[name: FormTools.FindTableByDataMember(ds: dataset, member: dataMember)];
        Guid entityId = (Guid)table.ExtendedProperties[key: "EntityId"];
        AbstractDataEntity entity = ps.SchemaProvider.RetrieveInstance(type: typeof(AbstractDataEntity), primaryKey: new ModelElementKey(id: entityId)) as AbstractDataEntity;
        return entity;
    }
    public void Screen(FormControlSet form, string xsltdoc)
    {
        WriteStartElement(element: "Menu");
        MakeXmlSections(form: form);
        WriteEndElement();
        CloseXml();
        XslCompiledTransform xslt = new XslCompiledTransform();
        using (StringReader sr = new StringReader(s: xsltdoc))
        using (XmlReader xslReader = XmlReader.Create(input: sr))
        {
            xslt.Load(stylesheet: xslReader);
        }
        SaveXslt(xslTransform: xslt, xmlWriter: XmlwriterSource);
    }
    public void Run()
    {
        if (!string.IsNullOrEmpty(value: XsltPath))
        {
            XslCompiledTransform processor = new XslCompiledTransform();
            processor.Load(stylesheetUri: XsltPath);
        }
        List<ISchemaItem> menulist = menuprovider.ChildItems.ToList();
        menulist.Sort();
        WriteStartElement(element: "Menu");
        CreateXml(menuSublist: menulist[index: 0]);
        WriteEndElement();
        CloseXml();
        if (!string.IsNullOrEmpty(value: xmlsourcefile))
        {
            SaveSchemaXml();
        }
        if (!string.IsNullOrEmpty(value: XsltPath) && !string.IsNullOrEmpty(value: RootFile))
        {
            XslCompiledTransform xslt = new XslCompiledTransform();
            xslt.Load(stylesheetUri: XsltPath);
            XmlWriterSettings settings = new XmlWriterSettings
            {
                Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                Indent = true
            };
            string outputPath = Path.Combine(path1: DirectoryPath, path2: RootFile);
            using (XmlWriter writer = XmlWriter.Create(outputFileName: outputPath, settings: settings))
            {
                SaveXslt(xslTransform: xslt, xmlWriter: writer);
            }
        }
    }
    private void SaveSchemaXml()
    {
        FileStream file = new FileStream(path: Path.Combine(path1: DirectoryPath, path2: xmlsourcefile), mode: FileMode.Create, access: FileAccess.Write);
        mstream.WriteTo(stream: file);
        file.Close();
        mstream.Close();
    }
    private void SaveXslt(XslCompiledTransform xslTransform, XmlWriter xmlWriter)
    {
        mstream.Seek(offset: 0, loc: SeekOrigin.Begin);
        XPathDocument doc = new XPathDocument(stream: mstream);
        xslTransform.Transform(input: doc, arguments: null, results: xmlWriter);
    }
    private void CreateXml(ISchemaItem menuSublist)
    {
        foreach (ISchemaItem menuitem in menuSublist.ChildItems)
        {
            WriteStartElement(element: "Menuitem", displayName: menuitem.NodeText, id: menuitem.Id.ToString(), typeitem: menuitem.GetType().Name);
            WriteElement(caption: "documentation",
                description: documentation.GetDocumentation(schemaItemId: menuitem.Id, docType: DocumentationType.USER_LONG_HELP));
            if (menuitem is FormReferenceMenuItem formItem)
            {
                MakeXmlSections(form: formItem.Screen);
            }
            CreateXml(menuSublist: menuitem);
            WriteEndElement();
        }
    }
    private void MakeXmlSections(FormControlSet form)
    {
        DataSet dataset = new DatasetGenerator(userDefinedParameters: false).CreateDataSet(ds: form.DataStructure);
        MakeXml(control: form.ChildItems[index: 0] as ControlSetItem, formItem: form, dataset: dataset, dataMember: null);
    }
    private void WriteStartElement(string element)
    {
        Xmlwriter.WriteStartElement(localName: element);
    }
    private void WriteStartElement(string element, string displayName, string id, string typeitem)
    {
        WriteStartElement(element: element);
        Xmlwriter.WriteAttributeString(localName: "DisplayName", value: displayName);
        Xmlwriter.WriteAttributeString(localName: "Id", value: id);
        Xmlwriter.WriteAttributeString(localName: "Type", value: typeitem);
    }
    private void WriteElement(string caption, string description)
    {
        if (!string.IsNullOrEmpty(value: description))
        {
            Xmlwriter.WriteElementString(localName: caption, value: description);
        }
    }
    private void WriteEndElement()
    {
        Xmlwriter.WriteEndElement();
    }
    private void CloseXml()
    {
        Xmlwriter.WriteEndDocument();
        Xmlwriter.Flush();
    }
}
