@port = 44357

// gets a file from the Attachment table by Id
GET https://localhost:{{port}}/api/public/Attachment/E65251F1-FD5B-4307-B0A7-4C9F5594A1AF


###
// fails and sends custom http return core
GET https://localhost:{{port}}/api/public/failingWorkflow
