#region license
/*
Copyright 2005 - 2018 Advantage Solutions, s. r. o.

This file is part of ORIGAM (http://www.origam.org).

ORIGAM is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ORIGAM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with ORIGAM. If not, see <http://www.gnu.org/licenses/>.
*/
#endregion

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AsMail.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/AsMail.xsd", IsNullable=false)]
public class Mails {
    
    /// <remarks/>
    public mailType Mail;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AsMail.xsd")]
public class mailType {
    
    /// <remarks/>
    public mailAddressType From;
    
    /// <remarks/>
    public mailAddressCollectionType To;
    
    /// <remarks/>
    public mailAddressCollectionType CC;
    
    /// <remarks/>
    public mailAddressCollectionType BCC;
    
    /// <remarks/>
    public string Subject;
    
    /// <remarks/>
    public mailTypeBody Body;
    
    /// <remarks/>
    public string MessageIdentifier;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AsMail.xsd")]
public class mailAddressType {
    
    /// <remarks/>
    public string Address;
    
    /// <remarks/>
    public string Name;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AsMail.xsd")]
public class mailTypeBodyHTML {
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AsMail.xsd")]
public class mailTypeBody {
    
    /// <remarks/>
    public mailTypeBodyHTML HTML;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AsMail.xsd")]
public class mailAddressCollectionType {
    
    /// <remarks/>
    public mailAddressType EmailAddress;
}
