export enum IAppMachineState {
  PASS_XSTATE_INIT = "PASS_XSTATE_INIT",
  GET_CREDENTIALS = "GET_CREDENTIALS",
  DO_LOGIN = "DO_LOGIN",
  DO_LOAD_MENU = "DO_LOAD_MENU",
  LOGGED_IN = "LOGGED_IN",
  LOGOUT = "LOGOUT"
}
