//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Origam.AI.Agent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Origam.AI.Agent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI agent needs Ai:ApiKey and Ai:Endpoint to be configured..
        /// </summary>
        internal static string AgentApiKeyAndEndpointMissing {
            get {
                return ResourceManager.GetString("AgentApiKeyAndEndpointMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI agent has no registered targets..
        /// </summary>
        internal static string AgentTargetsMissing {
            get {
                return ResourceManager.GetString("AgentTargetsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent target &apos;{0}&apos; registered no tool providers..
        /// </summary>
        internal static string AgentTargetWithoutToolProviders {
            get {
                return ResourceManager.GetString("AgentTargetWithoutToolProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias cannot be null or empty..
        /// </summary>
        internal static string AliasEmpty {
            get {
                return ResourceManager.GetString("AliasEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI agent cannot determine the Architect base url because the server reports no listening address..
        /// </summary>
        internal static string ArchitectBaseUrlUnknown {
            get {
                return ResourceManager.GetString("ArchitectBaseUrlUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached image could not be read..
        /// </summary>
        internal static string ImageInvalid {
            get {
                return ResourceManager.GetString("ImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached image is larger than the 10 MB limit..
        /// </summary>
        internal static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only PNG, JPEG, GIF and WebP images can be attached..
        /// </summary>
        internal static string ImageTypeNotSupported {
            get {
                return ResourceManager.GetString("ImageTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed with HTTP status {1}..
        /// </summary>
        internal static string OpenApiCallFailed {
            get {
                return ResourceManager.GetString("OpenApiCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt bundle &apos;{0}&apos; is missing..
        /// </summary>
        internal static string PromptBundleMissing {
            get {
                return ResourceManager.GetString("PromptBundleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt section &apos;{0}&apos; is missing from bundle &apos;{1}.md&apos; and from &apos;{2}.md&apos;..
        /// </summary>
        internal static string PromptSectionMissing {
            get {
                return ResourceManager.GetString("PromptSectionMissing", resourceCulture);
            }
        }
    }
}
