@port=44357

# put the access token to the file http-client.env.json
#{
#  "local": {
#    "access_token": "... "
#  }
#}

### Simple API tests intended for development

### InternalApI
GET https://localhost:{{port}}/internalApi/UIService/InitPortal
Authorization: Bearer {{access_token}}


### Modeled API 
GET https://localhost:{{port}}/api/private/link-report
Authorization: Bearer {{access_token}}


### Test Resource Owner Password Credentials (ROPC)
POST https://localhost:{{port}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=serverClient&
client_secret=serverSecret&
username=washi&
password=blabla&
scope=internal_api offline_access


### XsltDataPage with AllowCustomFilters=true

###
POST https://localhost:{{port}}/api/public/allDataWithFilter
Authorization: Bearer {{access_token}}

###
POST https://localhost:{{port}}/api/public/allDataWithFilter?_pageSize=1&_pageNumber=1
Authorization: Bearer {{access_token}}

###
POST https://localhost:{{port}}/api/public/allDataWithFilter
Authorization: Bearer {{access_token}}

{
  "filter": "[\"refTagInputSourceId\", \"contains\", \"L\"]",
  "filterLookups": {
    "refTagInputSourceId": "991a8bec-5169-4506-9457-7f91c27bb5fd"
  }
}

###
POST https://localhost:{{port}}/api/public/allDataWithFilter
Authorization: Bearer {{access_token}}

{
  "filter": "[\"refTagInputSourceId\", \"contains\", \"L\"]",
}

###
POST https://localhost:{{port}}/api/public/allDataWithFilter?_pageSize=2&_pageNumber=1
Authorization: Bearer {{access_token}}

{
  "filter": "[\"refTagInputSourceId\", \"contains\", \"L\"]",
  "filterLookups": {
    "refTagInputSourceId": "991a8bec-5169-4506-9457-7f91c27bb5fd"
  }
}

###
POST https://localhost:{{port}}/api/public/allDataWithFilter?_pageSize=2&_pageNumber=1
Authorization: Bearer {{access_token}}

{
  "filter": "[\"refTagInputSourceId\", \"contains\", \"L\"]",
  "filterLookups": {
    "refTagInputSourceId": "991a8bec-5169-4506-9457-7f91c27bb5fd"
  },
  "ordering": [
    { "columnId": "Integer1", "direction": "DESC" }
  ]
}

###
POST https://localhost:{{port}}/api/public/allDataWithFilter?_pageSize=2&_pageNumber=1
Authorization: Bearer {{access_token}}

{
  "ordering": [
    { "columnId": "Integer1", "direction": "DESC" }
  ]
}






