//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Origam.Architect.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Origam.Architect.Server.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string CategoryDocumentation {
            get {
                return ResourceManager.GetString("CategoryDocumentation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported deployment activity type.
        /// </summary>
        internal static string DeploymentScript_UnsupportedDeploymentActivityType {
            get {
                return ResourceManager.GetString("DeploymentScript_UnsupportedDeploymentActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model not saved. Please, save the model before setting the version..
        /// </summary>
        internal static string DeploymentScripts_ModelNotSavedBeforeVersionChange {
            get {
                return ResourceManager.GetString("DeploymentScripts_ModelNotSavedBeforeVersionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an item type that can be created here. Available types: {1}.
        /// </summary>
        internal static string NewItemTypeNotFound {
            get {
                return ResourceManager.GetString("NewItemTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} takes a reference to a {1}, but the id you passed belongs to a {2}. Find or create a {1} and pass its id instead..
        /// </summary>
        internal static string PropertyReferenceTypeNotValid {
            get {
                return ResourceManager.GetString("PropertyReferenceTypeNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This item is not in the model (id {0}). It was most likely discarded because it did not pass validation and was never saved..
        /// </summary>
        internal static string SchemaItemNotFound {
            get {
                return ResourceManager.GetString("SchemaItemNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter named {0} was not found among Input Parameters..
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for property {1}. Allowed values: {2}.
        /// </summary>
        internal static string PropertyEnumValueNotValid {
            get {
                return ResourceManager.GetString("PropertyEnumValueNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for property {1}. This property is a reference and takes the id (GUID) of an existing {2}, not its name. Look the item up and pass the id from the response.
        /// </summary>
        internal static string PropertyReferenceValueNotValid {
            get {
                return ResourceManager.GetString("PropertyReferenceValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT Validation.
        /// </summary>
        internal static string ValidationResultTitle {
            get {
                return ResourceManager.GetString("ValidationResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one field must be selected..
        /// </summary>
        internal static string Wizard_AtLeastOneFieldRequired {
            get {
                return ResourceManager.GetString("Wizard_AtLeastOneFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between function not found. Cannot create filter..
        /// </summary>
        internal static string Wizard_BetweenFunctionNotFound {
            get {
                return ResourceManager.GetString("Wizard_BetweenFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} not found.
        /// </summary>
        internal static string Wizard_ColumnNotFound {
            get {
                return ResourceManager.GetString("Wizard_ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column does not belong to an entity..
        /// </summary>
        internal static string Wizard_ColumnNotInEntity {
            get {
                return ResourceManager.GetString("Wizard_ColumnNotInEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active data service is not SQL-based..
        /// </summary>
        internal static string Wizard_DataServiceNotSql {
            get {
                return ResourceManager.GetString("Wizard_DataServiceNotSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DataStructure named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string Wizard_DataStructureAlreadyExists {
            get {
                return ResourceManager.GetString("Wizard_DataStructureAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a data structure entity, not an entity. Use the entity it points to: {1}..
        /// </summary>
        internal static string Wizard_DataStructureEntityUsedAsEntity {
            get {
                return ResourceManager.GetString("Wizard_DataStructureEntityUsedAsEntity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataStructure {0} not found.
        /// </summary>
        internal static string Wizard_DataStructureNotFound {
            get {
                return ResourceManager.GetString("Wizard_DataStructureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display field not found on entity..
        /// </summary>
        internal static string Wizard_DisplayFieldNotFound {
            get {
                return ResourceManager.GetString("Wizard_DisplayFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity has no primary key defined..
        /// </summary>
        internal static string Wizard_EntityHasNoPrimaryKey {
            get {
                return ResourceManager.GetString("Wizard_EntityHasNoPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity has no primary key defined. Cannot create lookup..
        /// </summary>
        internal static string Wizard_EntityHasNoPrimaryKeyForLookup {
            get {
                return ResourceManager.GetString("Wizard_EntityHasNoPrimaryKeyForLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} not found.
        /// </summary>
        internal static string Wizard_EntityNotFound {
            get {
                return ResourceManager.GetString("Wizard_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name is not set..
        /// </summary>
        internal static string Wizard_FieldNameNotSet {
            get {
                return ResourceManager.GetString("Wizard_FieldNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} not found on entity..
        /// </summary>
        internal static string Wizard_FieldNotFoundOnEntity {
            get {
                return ResourceManager.GetString("Wizard_FieldNotFoundOnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; cannot be placed on a screen automatically. Its data type has no default control, or it is a foreign key without a default lookup..
        /// </summary>
        internal static string Wizard_FieldCannotGenerateControl {
            get {
                return ResourceManager.GetString("Wizard_FieldCannotGenerateControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screen (FormControlSet) {0} not found.
        /// </summary>
        internal static string Wizard_FormControlSetNotFound {
            get {
                return ResourceManager.GetString("Wizard_FormControlSetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id filter not found on entity..
        /// </summary>
        internal static string Wizard_IdFilterNotFound {
            get {
                return ResourceManager.GetString("Wizard_IdFilterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List filter not found on entity..
        /// </summary>
        internal static string Wizard_ListFilterNotFound {
            get {
                return ResourceManager.GetString("Wizard_ListFilterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup name is required..
        /// </summary>
        internal static string Wizard_LookupNameRequired {
            get {
                return ResourceManager.GetString("Wizard_LookupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu caption is required..
        /// </summary>
        internal static string Wizard_MenuCaptionRequired {
            get {
                return ResourceManager.GetString("Wizard_MenuCaptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a {1}, not an entity. Pass the id of an entity..
        /// </summary>
        internal static string Wizard_NotAnEntity {
            get {
                return ResourceManager.GetString("Wizard_NotAnEntity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data structure name is required..
        /// </summary>
        internal static string Wizard_DataStructureNameRequired {
            get {
                return ResourceManager.GetString("Wizard_DataStructureNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screen section {0} not found.
        /// </summary>
        internal static string Wizard_ScreenSectionNotFound {
            get {
                return ResourceManager.GetString("Wizard_ScreenSectionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow {0} not found.
        /// </summary>
        internal static string Wizard_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Wizard_WorkflowNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database Entity (TableMappingItem) {0} not found.
        /// </summary>
        internal static string Wizard_TableEntityNotFound {
            get {
                return ResourceManager.GetString("Wizard_TableEntityNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screen Section name is required..
        /// </summary>
        internal static string Wizard_ScreenSectionNameRequired {
            get {
                return ResourceManager.GetString("Wizard_ScreenSectionNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Screen Section named "{0}" already exists..
        /// </summary>
        internal static string Wizard_ScreenSectionAlreadyExists {
            get {
                return ResourceManager.GetString("Wizard_ScreenSectionAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item {0} not found.
        /// </summary>
        internal static string Wizard_RoleItemNotFound {
            get {
                return ResourceManager.GetString("Wizard_RoleItemNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Role is only available for menu items with a specific role (not "*")..
        /// </summary>
        internal static string Wizard_RoleNotSpecific {
            get {
                return ResourceManager.GetString("Wizard_RoleNotSpecific", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no current deployment version. Create a deployment version and make it current first..
        /// </summary>
        internal static string Wizard_NoCurrentDeploymentVersion {
            get {
                return ResourceManager.GetString("Wizard_NoCurrentDeploymentVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screen name is required..
        /// </summary>
        internal static string Wizard_ScreenNameRequired {
            get {
                return ResourceManager.GetString("Wizard_ScreenNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown filter type &apos;{0}&apos;..
        /// </summary>
        internal static string Wizard_UnknownFilterType {
            get {
                return ResourceManager.GetString("Wizard_UnknownFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type {0} is not OrigamDataType..
        /// </summary>
        internal static string WrongParameterType {
            get {
                return ResourceManager.GetString("WrongParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT validation failed. See output for details..
        /// </summary>
        internal static string XsltValidationFailed {
            get {
                return ResourceManager.GetString("XsltValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT is valid..
        /// </summary>
        internal static string XsltValidationSuccess {
            get {
                return ResourceManager.GetString("XsltValidationSuccess", resourceCulture);
            }
        }
    }
}
