//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrigamArchitect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrigamArchitect.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string About_MenuItem {
            get {
                return ResourceManager.GetString("About_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Actions.
        /// </summary>
        internal static string Actions_MenuItem {
            get {
                return ResourceManager.GetString("Actions_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add to Deployment.
        /// </summary>
        internal static string AddToDeployment_Button {
            get {
                return ResourceManager.GetString("AddToDeployment_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add to Model.
        /// </summary>
        internal static string AddToModel_Button {
            get {
                return ResourceManager.GetString("AddToModel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the active user &apos;{0}&apos; to the user list?.
        /// </summary>
        internal static string AddUserToUserList_Question {
            get {
                return ResourceManager.GetString("AddUserToUserList_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string AppVersion_Label {
            get {
                return ResourceManager.GetString("AppVersion_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Model: {0}.
        /// </summary>
        internal static string AppVersionModel_Label {
            get {
                return ResourceManager.GetString("AppVersionModel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Attachements.
        /// </summary>
        internal static string Attachements_MenuItem {
            get {
                return ResourceManager.GetString("Attachements_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Log.
        /// </summary>
        internal static string AuditLog_MenuItem {
            get {
                return ResourceManager.GetString("AuditLog_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Data Model Documentation.
        /// </summary>
        internal static string BuildDataModelDocumentation_MenuItem {
            get {
                return ResourceManager.GetString("BuildDataModelDocumentation_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot login to the repository..
        /// </summary>
        internal static string CannotLogin_Message {
            get {
                return ResourceManager.GetString("CannotLogin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model repository database schema is not compatible. Cannot login to the repository..
        /// </summary>
        internal static string CannotLogin_Message2 {
            get {
                return ResourceManager.GetString("CannotLogin_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Login.
        /// </summary>
        internal static string CannotLogin_Title {
            get {
                return ResourceManager.GetString("CannotLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption:.
        /// </summary>
        internal static string Caption_Label {
            get {
                return ResourceManager.GetString("Caption_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated authentication cannot be used with Docker.\nPlease uncheck Integrated Authentication and fill in Username and Password..
        /// </summary>
        internal static string CheckIntegratedAuthentication_Message {
            get {
                return ResourceManager.GetString("CheckIntegratedAuthentication_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Close_MenuItem {
            get {
                return ResourceManager.GetString("Close_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close &amp;All.
        /// </summary>
        internal static string CloseAll_MenuItem {
            get {
                return ResourceManager.GetString("CloseAll_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All &amp;But This.
        /// </summary>
        internal static string CloseAllButThis_MenuItem {
            get {
                return ResourceManager.GetString("CloseAllButThis_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code_TableColumn {
            get {
                return ResourceManager.GetString("Code_TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Commands_PanelTitle {
            get {
                return ResourceManager.GetString("Commands_PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Community Support Forums.
        /// </summary>
        internal static string CommunityForums_MenuItem {
            get {
                return ResourceManager.GetString("CommunityForums_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration not found..
        /// </summary>
        internal static string ConfigurationNotFound_ExceptionMessage {
            get {
                return ResourceManager.GetString("ConfigurationNotFound_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connect.
        /// </summary>
        internal static string Connect_MenuItem {
            get {
                return ResourceManager.GetString("Connect_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the model repository....
        /// </summary>
        internal static string ConnectingToModelRepository_StatusText {
            get {
                return ResourceManager.GetString("ConnectingToModelRepository_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connection Configuration....
        /// </summary>
        internal static string ConnectionConfig_MenuItem {
            get {
                return ResourceManager.GetString("ConnectionConfig_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string ConnectionTitle {
            get {
                return ResourceManager.GetString("ConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Convert To.
        /// </summary>
        internal static string ConvertTo_MenuItem {
            get {
                return ResourceManager.GetString("ConvertTo_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count_TableColumn {
            get {
                return ResourceManager.GetString("Count_TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Empty.
        /// </summary>
        internal static string DatabaseEmptyTitle {
            get {
                return ResourceManager.GetString("DatabaseEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default model file does not exist..
        /// </summary>
        internal static string DefaultModelFileNotExists_Message {
            get {
                return ResourceManager.GetString("DefaultModelFileNotExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Delete_MenuItem {
            get {
                return ResourceManager.GetString("Delete_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Script.
        /// </summary>
        internal static string DeploymentScript_GroupBox {
            get {
                return ResourceManager.GetString("DeploymentScript_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Script Generator.
        /// </summary>
        internal static string DeploymentScriptGenerator_MenuItem {
            get {
                return ResourceManager.GetString("DeploymentScriptGenerator_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Script Generator.
        /// </summary>
        internal static string DeploymentScriptGenerator_Title {
            get {
                return ResourceManager.GetString("DeploymentScriptGenerator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Scripts.
        /// </summary>
        internal static string DeploymentScripts_Title {
            get {
                return ResourceManager.GetString("DeploymentScripts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Scripts Pending.
        /// </summary>
        internal static string DeploymentSctiptsPending_Title {
            get {
                return ResourceManager.GetString("DeploymentSctiptsPending_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like this is a new package. Would you like to run the deployment scripts of this package only, disregarding any dependencies? This could be useful if there are any deployment conflicts with the other packages..
        /// </summary>
        internal static string DeploySinglePackageQuestion {
            get {
                return ResourceManager.GetString("DeploySinglePackageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disconnect.
        /// </summary>
        internal static string Disconnect_MenuItem {
            get {
                return ResourceManager.GetString("Disconnect_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [disconnected].
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        internal static string DockPaneCaption_ToolTipAutoHide {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DockPaneCaption_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        internal static string DockPaneCaption_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DockPaneStrip_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Files.
        /// </summary>
        internal static string DockPaneStrip_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Documentation.
        /// </summary>
        internal static string Documentation_MenuItem {
            get {
                return ResourceManager.GetString("Documentation_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string DocumentToolStripText {
            get {
                return ResourceManager.GetString("DocumentToolStripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Window &amp;XML.
        /// </summary>
        internal static string DumpWindowXML_MenuItem {
            get {
                return ResourceManager.GetString("DumpWindowXML_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit in Diagram.
        /// </summary>
        internal static string EditInDiagram_MenuItem {
            get {
                return ResourceManager.GetString("EditInDiagram_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit item.
        /// </summary>
        internal static string EditItem_MenuItem {
            get {
                return ResourceManager.GetString("EditItem_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the database password..
        /// </summary>
        internal static string EnterDbPassword_Message {
            get {
                return ResourceManager.GetString("EnterDbPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the database server name..
        /// </summary>
        internal static string EnterDbServerName_Message {
            get {
                return ResourceManager.GetString("EnterDbServerName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the database user name..
        /// </summary>
        internal static string EnterDbUserName_Message {
            get {
                return ResourceManager.GetString("EnterDbUserName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Your Email.
        /// </summary>
        internal static string EnterEmail_name {
            get {
                return ResourceManager.GetString("EnterEmail_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the project name..
        /// </summary>
        internal static string EnterProjectName_Message {
            get {
                return ResourceManager.GetString("EnterProjectName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the sources folder..
        /// </summary>
        internal static string EnterSourceFolder_Message {
            get {
                return ResourceManager.GetString("EnterSourceFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the template folder..
        /// </summary>
        internal static string EnterTemplateFolder_Message {
            get {
                return ResourceManager.GetString("EnterTemplateFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Your Name.
        /// </summary>
        internal static string EnterUser_name {
            get {
                return ResourceManager.GetString("EnterUser_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the web application folder..
        /// </summary>
        internal static string EnterWebAppFolder_Message {
            get {
                return ResourceManager.GetString("EnterWebAppFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email..
        /// </summary>
        internal static string EnterWebEmail_Message {
            get {
                return ResourceManager.GetString("EnterWebEmail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter First Name..
        /// </summary>
        internal static string EnterWebFirstName_Message {
            get {
                return ResourceManager.GetString("EnterWebFirstName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the web password..
        /// </summary>
        internal static string EnterWebPassword_Message {
            get {
                return ResourceManager.GetString("EnterWebPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Surname..
        /// </summary>
        internal static string EnterWebSurname_Message {
            get {
                return ResourceManager.GetString("EnterWebSurname_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the web Username..
        /// </summary>
        internal static string EnterWebUserName_Message {
            get {
                return ResourceManager.GetString("EnterWebUserName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when processing a work queue command..
        /// </summary>
        internal static string ErrorWhenProcessingWorkQueueCommand_Message {
            get {
                return ResourceManager.GetString("ErrorWhenProcessingWorkQueueCommand_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while loading parameters.
        /// </summary>
        internal static string ErrorWhileLoadingParameters_Message {
            get {
                return ResourceManager.GetString("ErrorWhileLoadingParameters_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when exporting to excel.
        /// </summary>
        internal static string ExcelExportError_Message {
            get {
                return ResourceManager.GetString("ExcelExportError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExcepExport_Title {
            get {
                return ResourceManager.GetString("ExcepExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xecute.
        /// </summary>
        internal static string Execute_MenuItem {
            get {
                return ResourceManager.GetString("Execute_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment scripts have been created. Do you want to execute them?.
        /// </summary>
        internal static string ExecuteDeploymentScripts_Question {
            get {
                return ResourceManager.GetString("ExecuteDeploymentScripts_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit_MenuItem {
            get {
                return ResourceManager.GetString("Exit_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string File_Menu {
            get {
                return ResourceManager.GetString("File_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        internal static string Filter_Label {
            get {
                return ResourceManager.GetString("Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Dependencies.
        /// </summary>
        internal static string FindDependencies_MenuItem {
            get {
                return ResourceManager.GetString("FindDependencies_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find References.
        /// </summary>
        internal static string FindReferences_MenuItem {
            get {
                return ResourceManager.GetString("FindReferences_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find Schema Item Results.
        /// </summary>
        internal static string FindSchemaItemResults_MenuItem {
            get {
                return ResourceManager.GetString("FindSchemaItemResults_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish Task.
        /// </summary>
        internal static string FinishTask_MenuCommand {
            get {
                return ResourceManager.GetString("FinishTask_MenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when loading form.
        /// </summary>
        internal static string FormLoadingError_Message {
            get {
                return ResourceManager.GetString("FormLoadingError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate GUID.
        /// </summary>
        internal static string GenerateGUID_MenuItem {
            get {
                return ResourceManager.GetString("GenerateGUID_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Reflector Cache Methods.
        /// </summary>
        internal static string GenerateReflectorCacheMethods_MenuItem {
            get {
                return ResourceManager.GetString("GenerateReflectorCacheMethods_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string GenericError_Title {
            get {
                return ResourceManager.GetString("GenericError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Definition.
        /// </summary>
        internal static string GoToDefinition_MenuItem {
            get {
                return ResourceManager.GetString("GoToDefinition_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help_Menu {
            get {
                return ResourceManager.GetString("Help_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help_MenuItem {
            get {
                return ResourceManager.GetString("Help_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        internal static string Initialize_Title {
            get {
                return ResourceManager.GetString("Initialize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have privileges to run this operation.
        /// </summary>
        internal static string InsufficientPrivileges_Message {
            get {
                return ResourceManager.GetString("InsufficientPrivileges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License check failure.
        /// </summary>
        internal static string LicenseCheck_Failure_Label {
            get {
                return ResourceManager.GetString("LicenseCheck_Failure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License check failed.
        /// </summary>
        internal static string LicenseCheckFailed_Error {
            get {
                return ResourceManager.GetString("LicenseCheckFailed_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is expired.
        /// </summary>
        internal static string LicenseExpired_Label {
            get {
                return ResourceManager.GetString("LicenseExpired_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license is expired and we haven&apos;t been able to prolong your license ({0}). The license is prolonged each time you start Origam Architect and at the same time you are connected to the internet..
        /// </summary>
        internal static string LicenseExpired_Message {
            get {
                return ResourceManager.GetString("LicenseExpired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License expiration warning.
        /// </summary>
        internal static string LicenseWillExpire_Label {
            get {
                return ResourceManager.GetString("LicenseWillExpire_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license will expire in {0} days ({1}). You see this message because we haven&apos;t been able to prolong your license ({2}). The license is prolonged each time you start Origam Architect and at the same time you are connected to the internet. So you can continue using the Architect offline but only for {0} days..
        /// </summary>
        internal static string LicenseWillExpire_Message {
            get {
                return ResourceManager.GetString("LicenseWillExpire_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Model.
        /// </summary>
        internal static string LoadingModelErrorTitle {
            get {
                return ResourceManager.GetString("LoadingModelErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Log.
        /// </summary>
        internal static string Log_MenuItem {
            get {
                return ResourceManager.GetString("Log_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string LoginForm_Error_Label {
            get {
                return ResourceManager.GetString("LoginForm_Error_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting  from server.
        /// </summary>
        internal static string LoginForm_ErrorGettingLicense_Label {
            get {
                return ResourceManager.GetString("LoginForm_ErrorGettingLicense_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get a license ({0}) from server. Please contact Origam.com..
        /// </summary>
        internal static string LoginForm_ErrorGettingLicense_Message {
            get {
                return ResourceManager.GetString("LoginForm_ErrorGettingLicense_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is a mandatory field. Please fill in a password..
        /// </summary>
        internal static string LoginForm_PasswordIsMandatory {
            get {
                return ResourceManager.GetString("LoginForm_PasswordIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginForm_Unsuccessfull_Label {
            get {
                return ResourceManager.GetString("LoginForm_Unsuccessfull_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is a mandatory field. Please fill in a username..
        /// </summary>
        internal static string LoginForm_UsernameIsMandatory {
            get {
                return ResourceManager.GetString("LoginForm_UsernameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login warning.
        /// </summary>
        internal static string LoginForm_Warning_Label {
            get {
                return ResourceManager.GetString("LoginForm_Warning_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Massages_TabText {
            get {
                return ResourceManager.GetString("Massages_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Massages_XmlItem {
            get {
                return ResourceManager.GetString("Massages_XmlItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu_MenuItem {
            get {
                return ResourceManager.GetString("Menu_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages_PanelTitle {
            get {
                return ResourceManager.GetString("Messages_PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Model.
        /// </summary>
        internal static string Model_Menu {
            get {
                return ResourceManager.GetString("Model_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Model Browser.
        /// </summary>
        internal static string ModelBrowser_MenuItem {
            get {
                return ResourceManager.GetString("ModelBrowser_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Changed.
        /// </summary>
        internal static string ModelChanged_Title {
            get {
                return ResourceManager.GetString("ModelChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current model has been changed. Do you want to save it to the repository?.
        /// </summary>
        internal static string ModelChangedSaveToRepQuestion {
            get {
                return ResourceManager.GetString("ModelChangedSaveToRepQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model version is not the same as database version. {0} Model version: {1} Database version: {2}.
        /// </summary>
        internal static string ModelDatabaseVersionMissmatch_Message {
            get {
                return ResourceManager.GetString("ModelDatabaseVersionMissmatch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model version is not the same as database version. Please contact your administrator. {0} Model version: {1} Database version: {2}.
        /// </summary>
        internal static string ModelDatabaseVersionMissmatchNoAdmin_Message {
            get {
                return ResourceManager.GetString("ModelDatabaseVersionMissmatchNoAdmin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated model elements are now shown in the search results..
        /// </summary>
        internal static string ModelElementsUpdate_Message {
            get {
                return ResourceManager.GetString("ModelElementsUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model successfully generated..
        /// </summary>
        internal static string ModelGeneratedMassage {
            get {
                return ResourceManager.GetString("ModelGeneratedMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model generation not supported for {0}.
        /// </summary>
        internal static string ModelGenerationNotSupported_Message {
            get {
                return ResourceManager.GetString("ModelGenerationNotSupported_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Generation.
        /// </summary>
        internal static string ModelGenerationTitle {
            get {
                return ResourceManager.GetString("ModelGenerationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model does not contain package OrigamRoot. Cannot run the application..
        /// </summary>
        internal static string ModelMissingMessage {
            get {
                return ResourceManager.GetString("ModelMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Model Version: {0}{1}.
        /// </summary>
        internal static string ModelVersion_Title {
            get {
                return ResourceManager.GetString("ModelVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model OrigamRoot version must be greater than 5.0.0 Cannot run the application..
        /// </summary>
        internal static string ModelVersionErrorMessage {
            get {
                return ResourceManager.GetString("ModelVersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Version.
        /// </summary>
        internal static string ModelVersionTitle {
            get {
                return ResourceManager.GetString("ModelVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Move To Package.
        /// </summary>
        internal static string MoveToPackage_MenuItem {
            get {
                return ResourceManager.GetString("MoveToPackage_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_TableColumn {
            get {
                return ResourceManager.GetString("Name_TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains invalid characters. Use letters and numbers. Database name, URL and folders will be created using the name..
        /// </summary>
        internal static string NameContainsInvalidChars_Message {
            get {
                return ResourceManager.GetString("NameContainsInvalidChars_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string New_MenuItem {
            get {
                return ResourceManager.GetString("New_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;Group.
        /// </summary>
        internal static string NewGroup_MenuItem {
            get {
                return ResourceManager.GetString("NewGroup_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Project....
        /// </summary>
        internal static string NewProject_MenuItem {
            get {
                return ResourceManager.GetString("NewProject_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Failed.
        /// </summary>
        internal static string NewProjectFailed_Message {
            get {
                return ResourceManager.GetString("NewProjectFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Wizard.
        /// </summary>
        internal static string NewProjectWizard_Title {
            get {
                return ResourceManager.GetString("NewProjectWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open_Button {
            get {
                return ResourceManager.GetString("Open_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options_Label {
            get {
                return ResourceManager.GetString("Options_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORIGAM Architect.
        /// </summary>
        internal static string OrigamArchitect_Title {
            get {
                return ResourceManager.GetString("OrigamArchitect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output.
        /// </summary>
        internal static string Output_MenuItem {
            get {
                return ResourceManager.GetString("Output_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Package Browser.
        /// </summary>
        internal static string PackageBrowser_MenuItem {
            get {
                return ResourceManager.GetString("PackageBrowser_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is not Number!.
        /// </summary>
        internal static string PortError {
            get {
                return ResourceManager.GetString("PortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string ProcessesTabText {
            get {
                return ResourceManager.GetString("ProcessesTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process List.
        /// </summary>
        internal static string ProcessList {
            get {
                return ResourceManager.GetString("ProcessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Properties.
        /// </summary>
        internal static string Properties_MenuItem {
            get {
                return ResourceManager.GetString("Properties_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment script updated successfully. Do you want to put the generated items to the search results?.
        /// </summary>
        internal static string PutItemsToSearchResultQuestion {
            get {
                return ResourceManager.GetString("PutItemsToSearchResultQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rebuild Localization Files.
        /// </summary>
        internal static string RebuildLocalizationFiles_MenuItem {
            get {
                return ResourceManager.GetString("RebuildLocalizationFiles_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh_Button {
            get {
                return ResourceManager.GetString("Refresh_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string Refresh_MenuCommand {
            get {
                return ResourceManager.GetString("Refresh_MenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary error ({0}). Please contact Origam.com by if it repeats..
        /// </summary>
        internal static string RegisterAndLoginForm_TemporaryHttpError {
            get {
                return ResourceManager.GetString("RegisterAndLoginForm_TemporaryHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been successful, but couldn&apos;t send confirmation email ({0})..
        /// </summary>
        internal static string RegisterForm_CouldNotSendConfirmationMail_Message {
            get {
                return ResourceManager.GetString("RegisterForm_CouldNotSendConfirmationMail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error.
        /// </summary>
        internal static string RegisterForm_Error_Label {
            get {
                return ResourceManager.GetString("RegisterForm_Error_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration success.
        /// </summary>
        internal static string RegisterForm_Success_Label {
            get {
                return ResourceManager.GetString("RegisterForm_Success_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered into Origam.com! We have just sent an e-mail with a confirmation link to your email address `{0}&apos;. Please check your e-mail and confirm your email address by clicking on a confirmation link in the e-mail..
        /// </summary>
        internal static string RegisterForm_Success_Message {
            get {
                return ResourceManager.GetString("RegisterForm_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration warning.
        /// </summary>
        internal static string RegisterForm_Warning_Label {
            get {
                return ResourceManager.GetString("RegisterForm_Warning_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error. Please contact Origam.com.
        /// </summary>
        internal static string RegisterLoginForm_UnexpectedError_Message {
            get {
                return ResourceManager.GetString("RegisterLoginForm_UnexpectedError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error. Please contact Origam.com ({0}).
        /// </summary>
        internal static string RegisterLoginForm_UnexpectedErrorWithMessage_Message {
            get {
                return ResourceManager.GetString("RegisterLoginForm_UnexpectedErrorWithMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark_TableColumn {
            get {
                return ResourceManager.GetString("Remark_TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Repeat New.
        /// </summary>
        internal static string RepeatNew_MenuItem {
            get {
                return ResourceManager.GetString("RepeatNew_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository seems to be empty. Do you want to initialize repository?.
        /// </summary>
        internal static string RepositoryInitializeQuestion {
            get {
                return ResourceManager.GetString("RepositoryInitializeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository login failed. {0}.
        /// </summary>
        internal static string RepositoryLoginFailedMessage {
            get {
                return ResourceManager.GetString("RepositoryLoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Login Failed.
        /// </summary>
        internal static string RepositoryLoginFailedTitle {
            get {
                return ResourceManager.GetString("RepositoryLoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset User Cache.
        /// </summary>
        internal static string ResetUserCache_MenuItem {
            get {
                return ResourceManager.GetString("ResetUserCache_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} result(s)..
        /// </summary>
        internal static string ResultCountMassage {
            get {
                return ResourceManager.GetString("ResultCountMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results_Label {
            get {
                return ResourceManager.GetString("Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results_Title {
            get {
                return ResourceManager.GetString("Results_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry when finished.
        /// </summary>
        internal static string Retry_MenuCommand {
            get {
                return ResourceManager.GetString("Retry_MenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        internal static string Role_Label {
            get {
                return ResourceManager.GetString("Role_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Trace.
        /// </summary>
        internal static string RuleTrace_MenuItem {
            get {
                return ResourceManager.GetString("RuleTrace_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model has been updated and update scripts are pending. Do you want to execute the deployment scripts?.
        /// </summary>
        internal static string RunDeploymentScriptsQuestion {
            get {
                return ResourceManager.GetString("RunDeploymentScriptsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data database is empty. Do you want to execute the initial database scripts?.
        /// </summary>
        internal static string RunInitDatabaseScriptsQuestion {
            get {
                return ResourceManager.GetString("RunInitDatabaseScriptsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Update Actions.
        /// </summary>
        internal static string RunRefreshActions_MenuItem {
            get {
                return ResourceManager.GetString("RunRefreshActions_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run Update Scripts.
        /// </summary>
        internal static string RunUpdateScripts_MenuItem {
            get {
                return ResourceManager.GetString("RunUpdateScripts_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa&amp;ve.
        /// </summary>
        internal static string Save_MenuCommand {
            get {
                return ResourceManager.GetString("Save_MenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model changes were not saved. Do you want to save them before the server restart?.
        /// </summary>
        internal static string SaveModelChanges_Question {
            get {
                return ResourceManager.GetString("SaveModelChanges_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SavemodelChanges_Title {
            get {
                return ResourceManager.GetString("SavemodelChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save XML result.
        /// </summary>
        internal static string SaveXmlResult_Title {
            get {
                return ResourceManager.GetString("SaveXmlResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchResultTitle {
            get {
                return ResourceManager.GetString("SearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Script.
        /// </summary>
        internal static string SelectDeploymentTitle {
            get {
                return ResourceManager.GetString("SelectDeploymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the deployment type..
        /// </summary>
        internal static string SelectDeploymentType_Message {
            get {
                return ResourceManager.GetString("SelectDeploymentType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select deployment version..
        /// </summary>
        internal static string SelectDeploymentVersionMessage {
            get {
                return ResourceManager.GetString("SelectDeploymentVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the web root..
        /// </summary>
        internal static string SelectWebRoot_Message {
            get {
                return ResourceManager.GetString("SelectWebRoot_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Server Log.
        /// </summary>
        internal static string ServerLog_MenuItem {
            get {
                return ResourceManager.GetString("ServerLog_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerUrl not set in the settings..
        /// </summary>
        internal static string ServerUrlNotSet_Message {
            get {
                return ResourceManager.GetString("ServerUrlNotSet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Web Application.
        /// </summary>
        internal static string ServerUrlNotSet_Title {
            get {
                return ResourceManager.GetString("ServerUrlNotSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Server(s).
        /// </summary>
        internal static string SetServerRestart_MenuItem {
            get {
                return ResourceManager.GetString("SetServerRestart_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rule Trace.
        /// </summary>
        internal static string ShowRuleTrace_MenuItem {
            get {
                return ResourceManager.GetString("ShowRuleTrace_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Trace.
        /// </summary>
        internal static string ShowTrace_MenuItem {
            get {
                return ResourceManager.GetString("ShowTrace_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Web Application.
        /// </summary>
        internal static string ShowWebApplication_MenuItem {
            get {
                return ResourceManager.GetString("ShowWebApplication_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCode_GroupBox {
            get {
                return ResourceManager.GetString("SourceCode_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources folder does not exist..
        /// </summary>
        internal static string SourceFolderNotExists_Message {
            get {
                return ResourceManager.GetString("SourceFolderNotExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer.
        /// </summary>
        internal static string SourceXml_MenuItem {
            get {
                return ResourceManager.GetString("SourceXml_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Console.
        /// </summary>
        internal static string SqlConsole_MenuItem {
            get {
                return ResourceManager.GetString("SqlConsole_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Template or fill git repository.
        /// </summary>
        internal static string TemplateNotSelect {
            get {
                return ResourceManager.GetString("TemplateNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string Tools_Menu {
            get {
                return ResourceManager.GetString("Tools_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string ToolsToolStripText {
            get {
                return ResourceManager.GetString("ToolsToolStripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type_TableColumn {
            get {
                return ResourceManager.GetString("Type_TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Database Type.
        /// </summary>
        internal static string UnknownDatabaseType {
            get {
                return ResourceManager.GetString("UnknownDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown deployment type selected..
        /// </summary>
        internal static string UnknownDeploymentType {
            get {
                return ResourceManager.GetString("UnknownDeploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model repository database schema is older version. Do you want to upgrade the model repository?.
        /// </summary>
        internal static string UpgradeModelQuestion {
            get {
                return ResourceManager.GetString("UpgradeModelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string UpgradeModelTitle {
            get {
                return ResourceManager.GetString("UpgradeModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Label {
            get {
                return ResourceManager.GetString("Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; version info &gt;&gt;.
        /// </summary>
        internal static string VersionInfo_Label {
            get {
                return ResourceManager.GetString("VersionInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string View_Menu {
            get {
                return ResourceManager.GetString("View_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application folder does not exist..
        /// </summary>
        internal static string WebAppFolderNotExists_Message {
            get {
                return ResourceManager.GetString("WebAppFolderNotExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal!.
        /// </summary>
        internal static string WebPasswordNotMatch_Message {
            get {
                return ResourceManager.GetString("WebPasswordNotMatch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string Window_Menu {
            get {
                return ResourceManager.GetString("Window_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Trace.
        /// </summary>
        internal static string WorkFlowTrace_MenuItem {
            get {
                return ResourceManager.GetString("WorkFlowTrace_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Workflow Watch.
        /// </summary>
        internal static string WorkflowWatch_MenuItem {
            get {
                return ResourceManager.GetString("WorkflowWatch_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Work Queue.
        /// </summary>
        internal static string WorkQueue_MenuItem {
            get {
                return ResourceManager.GetString("WorkQueue_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Queue Command.
        /// </summary>
        internal static string WorkQueueCommand_Title {
            get {
                return ResourceManager.GetString("WorkQueueCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Queues.
        /// </summary>
        internal static string WorkQueues_Title {
            get {
                return ResourceManager.GetString("WorkQueues_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show XML.
        /// </summary>
        internal static string XmlConsole {
            get {
                return ResourceManager.GetString("XmlConsole", resourceCulture);
            }
        }
    }
}
