// Input file for REST client for Visual Studio Code 
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@port = 44356
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUFRMRTU0MFxccGF2ZWwiLCJuYmYiOiIxNTQyODMwNTc3IiwiZXhwIjoiMTU0MjkxNjk3NyJ9.YVxGKmYrvZdTkenY26uaT6toMRl8b30dJmNpH1xjgbE

/// --- TokenController --- ///
// send user and password to get new token, put the received 
// value to the token variable defined above
POST https://localhost:{{port}}/api/Token/Create
content-Type: application/x-www-form-urlencoded; charset=UTF-8

password=PTLE540\pavel
&username=PTLE540\pavel

###

/// --- MetaDataController --- ///

GET https://localhost:{{port}}/api/MetaData/GetMenu
Authorization : Bearer {{token}}

###

GET https://localhost:{{port}}/api/MetaData/GetScreeSection?id=b2a2194c-c2a5-4236-837a-08c1b720fc96
Authorization : Bearer {{token}}

###

/// --- DataController --- ///
GET https://localhost:{{port}}/api/Data/Entities
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "filter": "",
  "ordering": [["bla2","asc"]],
  "rowLimit": "5",
  "columnNames": ["bla1", "bla2", "bla3"]
}

###

GET https://localhost:{{port}}/api/Data/Entities
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "filter": "[\"bla3\",\"like\",\"%hu%\"]",
  "ordering": [["bla2","desc"]],
  "rowLimit": "5",
  "columnNames": ["bla1", "bla2", "bla3"]
}

###

GET https://localhost:{{port}}/api/Data/Entities
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "filter": "",
  "ordering": [["bla2","desc"]],
  "rowLimit": "2",
  "columnNames": ["bla1", "bla2", "bla3"]
}

###

PUT https://localhost:{{port}}/api/Data/Entities
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "rowId": "F3109DD0-52AD-434E-964A-310ADA3925DB",
  "newValues" : {
    "bla2":"333",
    "testDate": "2011-10-01T01:18:54.6652000-12:00",
    "testFloat": "124.57"
    },
}

###

POST https://localhost:{{port}}/api/Data/Entities
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "newValues" : {
    "bla1": "true",
    "bla2": "3",
    "bla3": "tri",
    "testDate": "2011-10-01T01:18:54.6652000-12:00",
    "testFloat": "124.57"
    },
}

###

DELETE https://localhost:{{port}}/api/Data/Entities
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "rowIdToDelete" : "3908AC74-AA30-4AD7-B9A5-F8125AC7129A",
}

###

POST https://localhost:{{port}}/api/Data/DeleteEntityData
Authorization : Bearer {{token}}
content-type: application/json

{
  "dataStructureEntityId": "3ab73ed4-b216-44de-83c5-0868472e4927",
  "rowIdToDelete" : "6905EFFE-FBB3-4CDE-B07F-01CAB6F2C5C8",
}
