using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.XPath;
using System.Xml.Xsl;
using Mvp.Xml.Common.Xsl;
using Mvp.Xml.Exslt;
using Origam.DA.Service;
using Origam.Gui.Win;
using Origam.Schema;
using Origam.Schema.GuiModel;
using Origam.Schema.MenuModel;
using Origam.Workbench.Services;

namespace Origam.DocGenerator
{
    class DocCreate
    {
        private string Path { get; set; }
        private MultiXmlTextWriter Xmlwriter { get; set; }
        
        private IDocumentationService documentation;
        private MenuSchemaItemProvider menuprovider = new MenuSchemaItemProvider();
        private readonly FilePersistenceProvider persprovider;
        private readonly string XsltPath;
        private readonly MemoryStream mstream ;
        private readonly string RootFile ;

        public DocCreate(string path,string xslt, string rootfile, FileStorageDocumentationService documentation1,FilePersistenceProvider persprovider)
        {
            if(string.IsNullOrEmpty(path))
            {
                 throw new Exception("Path for Export is not set!");
            }
            if (string.IsNullOrEmpty(xslt))
            {
                throw new Exception("Xlst template is not set!");
            }

            if (string.IsNullOrEmpty(rootfile))
            {
                throw new Exception("RootFileName is not set!");
            }

            RootFile = rootfile;
            XsltPath = xslt;
            this.Path = string.Join("", path.Split(System.IO.Path.GetInvalidPathChars())); ;
            documentation = documentation1 ?? throw new Exception("Documentation  is not set!");
            menuprovider.PersistenceProvider = persprovider ?? throw new Exception("PersistenceProvider is not set!"); 
            this.persprovider = persprovider;
            mstream = new MemoryStream();
            CreateWriter();
        }

       
        private void CreateWriter()
        {
            Xmlwriter = new MultiXmlTextWriter(mstream, Encoding.UTF8)
            {
                Formatting = Formatting.Indented
            };
            Xmlwriter.WriteStartDocument();
            Xmlwriter.WriteComment("This file is generated by the program.(" + DateTime.Now + ")");
        }

        private void MakeXml( ControlSetItem control, FormControlSet formItem, DataSet dataset,string dataMember)
        {
            string caption = "";
            string gridCaption = "";
            string bindingMember = "";
            string panelTitle = "";
            int tabIndex = 0;
            string section = "";

            foreach (PropertyValueItem property in control.ChildItemsByType(PropertyValueItem.ItemTypeConst))
            {
                if (property.ControlPropertyItem.Name == "TabIndex")
                {
                    tabIndex = property.IntValue;
                }

                if (property.ControlPropertyItem.Name == "Caption")
                {
                    caption = property.Value;
                }

                if (property.ControlPropertyItem.Name == "GridColumnCaption")
                {
                    gridCaption = property.Value;
                }

                if (property.ControlPropertyItem.Name == "PanelTitle")
                {
                    panelTitle = property.Value;
                }

                if (control.ControlItem.IsComplexType && property.ControlPropertyItem.Name == "DataMember")
                {
                    dataMember = property.Value;
                }
            }

            caption = (gridCaption == "" | gridCaption == null) ? caption : gridCaption;
            foreach (PropertyBindingInfo bindItem in control.ChildItemsByType(PropertyBindingInfo.ItemTypeConst))
            {
                bindingMember = bindItem.Value;
            }

            if (bindingMember != "")
            {
                DataTable table = dataset.Tables[FormGenerator.FindTableByDataMember(dataset, dataMember)];

                if (!table.Columns.Contains(bindingMember)) throw new Exception("Field '" + bindingMember + "' not found in a data structure for the form '" + control.RootItem.Path + "'");

                if (string.IsNullOrEmpty(caption))
                {
                    caption = table.Columns[bindingMember].Caption;
                }
                Guid id = (Guid)table.Columns[bindingMember].ExtendedProperties["Id"];
                WriteStartElement("Field", caption);
                string docc = documentation.GetDocumentation(id, DocumentationType.USER_LONG_HELP);
                WriteElement("description", docc);
            }

            ArrayList sortedControls;
            if (control.ControlItem.IsComplexType)
            {
                string doc = documentation.GetDocumentation(control.ControlItem.PanelControlSet.Id, DocumentationType.USER_LONG_HELP);

                if (panelTitle!= "")
                {
                    section = panelTitle;
                }
                else
                {
                    section = "Panel";
                }
                if (string.IsNullOrEmpty(section))
                {
                    section = "Panel";
                }
                WriteStartElement("Section", section);
                WriteElement("description", doc);
                sortedControls = control.ControlItem.PanelControlSet.ChildItems[0].ChildItemsByType(ControlSetItem.ItemTypeConst);
            }
            else
            {
                sortedControls = control.ChildItemsByType(ControlSetItem.ItemTypeConst);
            }

            sortedControls.Sort(new ControlSetItemComparer());
            foreach (ControlSetItem subControl in sortedControls)
            {
                MakeXml(subControl,formItem,dataset, dataMember);
            }
            if (bindingMember != "")
            {
                WriteEndElement();
            }
            if (section != "")
            {
                WriteEndElement();
            }
        }

        public Boolean Run()
        {
            if(!string.IsNullOrEmpty(XsltPath))
            {
                MvpXslTransform processor = new MvpXslTransform(false);
                try
                { 
                    processor.Load(XsltPath);
                } catch (XsltException)
                {
                    //asi potreba nekam neco zapsat !?
                    return false;
                }
            }
            List<AbstractSchemaItem> menulist = menuprovider.ChildItems.ToList();
            menulist.Sort();
            WriteStartElement("Menu");
            CreateXml(menulist[0]);
            WriteEndElement();
            CloseXml();
            //SaveSchemaXml();
            SaveXlts();
            return true;
        }

        private void SaveSchemaXml()
        {
            //for test only
            FileStream file = new FileStream(Path + "schemaXml.xml",  FileMode.Create, FileAccess.Write);
            mstream.WriteTo(file);
            file.Close();
            mstream.Close();
        }

        private void SaveXlts()
        {
            TextWriter text = new StringWriter();
            mstream.Seek(0, SeekOrigin.Begin);
            XPathDocument doc = new XPathDocument(mstream);
            XslCompiledTransform xslttransform = new XslCompiledTransform();
            xslttransform.Load(XsltPath);
            MultiXmlTextWriter multiWriter = new MultiXmlTextWriter(Path + RootFile ,Encoding.UTF8);
            xslttransform.Transform(doc, null, multiWriter);
        }

        private string RemoveIllegalCharactersFromPath(string fileName)
        {
            return string.Join("", fileName.Split(System.IO.Path.GetInvalidFileNameChars()));
        }

        private void CreateXml(AbstractSchemaItem menuSublist)
        {
            foreach (AbstractSchemaItem menuitem in menuSublist.ChildItems)
            {
                WriteStartElement("Menuitem", menuitem.NodeText);
                string doc = documentation.GetDocumentation(menuitem.Id, DocumentationType.USER_LONG_HELP);
                WriteElement("documentation", doc);
                if (menuitem is FormReferenceMenuItem formItem)
                {
                    FormControlSet form = formItem.Screen;
                    DataSet dataset = new DatasetGenerator(false).CreateDataSet(form.DataStructure);
                    MakeXml(form.ChildItems[0] as ControlSetItem, form, dataset,null);
                }
                WriteEndElement();
                CreateXml(menuitem);
            }
        }

        private void WriteStartElement(string element)
        {
            element = StripNonValidXMLCharacters(element);
            Xmlwriter.WriteStartElement(element);
        }

        private void WriteStartElement(string element,string title)
        {
            element = StripNonValidXMLCharacters(element);
            title = StripNonValidXMLCharacters(title);

            Xmlwriter.WriteStartElement(element);
            Xmlwriter.WriteAttributeString("DisplayName", title);
        }

        private void WriteElement(string caption,string description)
        {
            caption = StripNonValidXMLCharacters(caption);
            description = StripNonValidXMLCharacters(description);

            if (!string.IsNullOrEmpty(description))
            { 
                Xmlwriter.WriteElementString(caption, description);
            }
        }

        private void WriteEndElement()
        {
            Xmlwriter.WriteEndElement();
        }

        private void CloseXml()
        {
            Xmlwriter.WriteEndDocument();
            Xmlwriter.Flush();
        }
        public string StripNonValidXMLCharacters(string textIn)
        {
            XmlDocument doc = new XmlDocument();
            XmlNode node = doc.CreateElement("root");
            node.InnerText = textIn;
            return node.InnerXml;
        }
    }
}
